#!/bin/sh

if ! test -f nmod; then
	wget --no-check-certificate http://github.com/jeromeetienne/nmod/raw/master/nmod
	chmod a+x nmod
fi
NMOD='./nmod install'

fetch() {
	test -d node_modules/$1 || $NMOD $1
}

#fetch stereo
fetch cookie-sessions
fetch formidable
#fetch formaline
fetch qs
fetch stack
fetch simple-mime
fetch mongodb
fetch underscore
#fetch creationix
#fetch node-proxy
#fetch now
#fetch dnode
#fetch underscore-data
